### ISSUE TITLE
Support for embedded song/album/playlist from Spotify

### ISSUE THREAD

**Issue by pxntus** [tribut/ttrss-videoframes#17]
I see this now and then among my rss subscriptions.

More information here: https://developer.spotify.com/technologies/widgets/spotify-play-button/

**Comment by Raman325** [comment]
Just created this PR to add support #25

**Comment by tribut** [comment]
Closed via https://github.com/tribut/ttrss-videoframes/commit/b91eb3beba8d6e2fa41bdd0c547b595e2247d497
